yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  "add-nx-to-monorepo@*":
    dependencies:
      "tslib": "*"
      "inquirer": "*"
  babel-plugin-const-enum@*:
    dependencies:
      "@babel/generator": "*"
  babel-plugin-transform-typescript-metadata@*:
    dependencies:
      "@babel/core": "*"
  
